#!/bin/bash
set -e # If any command fails, stop execution of the hook with that error
#
apt-get -y install python-cheetah git apache2 libapache2-mod-php php-sqlite3 sqlite3 php-xml

# delete old install
if [ -f /var/www/html/ebooks/config.php ]; then
  rm -rf /var/www/html/ebooks
fi

# Grab ebbok-wunschliste from upstream.
status-set maintenance "Fetching and installing ebbok-wunschliste"
git clone https://github.com/eumel8/ebook-wunschliste.git /var/www/html/ebooks
chown -R www-data:www-data /var/www/html/ebooks

sed -i -e "s/^\$AWSSecretKey.*/\$AWSSecretKey='${AWSSecretKey}';/" /var/www/html/ebooks/config.php
sed -i -e "s/^\$AWSAccessKeyId.*/\$AWSAccessKeyId='${AWSSecretKey}';/" /var/www/html/ebooks/config.php
sed -i -e "s/^\$AssociateTag.*/\$AssociateTag='${AssociateTag}';/" /var/www/html/ebooks/config.php

# cheetah fill --env -p templates/config.php > /var/www/html/ebooks/config.php

# set apache conf
status-set maintenance "Creating apache2 configuration"
cat <<EOF > /etc/apache2/sites-available/ebook-wunschliste.conf
<VirtualHost *:80>
  ServerAdmin webmaster@localhost
  DocumentRoot /var/www/html/ebooks
  <Directory /var/www/html/ebooks>
    Options Indexes FollowSymLinks MultiViews
    AllowOverride All
    Require all granted
  </Directory>
  ErrorLog \${APACHE_LOG_DIR}/ebook-wunschliste-error.log
  LogLevel warn
  CustomLog \${APACHE_LOG_DIR}/ebook-wunschliste-access.log combined
</VirtualHost>
EOF
a2dissite 000-default
a2ensite ebook-wunschliste
systemctl restart apache2.service
status-set active "Installation finished"

